server {
    listen 80;
    server_name legal.nexusx6.com.br;

    root /var/www/legal.nexusx6.com.br/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
